### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by anayyar82** [lianhuiwang/spark-sql-yarn#2]
Getting issue like : 

Error: Could not find or load main class org.apache.spark.sql.client.JavaSparkSQLClient

**Comment by lianhuiwang** [comment]
@anayyar82 which version you used? I have only used 1.6 version.
At firstly, we need to output 'spark.sql.yarn.files ./target/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar' to spark-defaults.conf.
or we can try use commond 'spark-submit --conf spark.sql.yarn.files=./target/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar'.
If you have any problems, please let me know. Also we can maintain it together. Thanks.

**Comment by anayyar82** [comment]
Thanks for looking, i am using 1.6 only. 

here are things i am doing ... 

Build the MAVEN File and deployed to cluster  and running via below command : 

 spark-submit --class org.apache.spark.sql.client.JavaSparkSQLClient spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar spark-defaults.conf /home/sg226503/ "select 1+2"

Using properties file: spark-defaults.conf
Adding default property: spark.sql.yarn.files=/home/sg226503/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar
Adding default property: spark.yarn.queue=root.default
Adding default property: spark.app.name=sparkSQL-client
Adding default property: spark.yarn.user.classpath.first=true
Adding default property: spark.master=yarn-cluster
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/jars/avro-tools-1.7.6-cdh5.5.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
16/07/28 10:54:00 WARN SparkConf: The configuration key 'spark.yarn.user.classpath.first' has been deprecated as of Spark 1.3 and may be removed in the future. Please use spark.{driver,executor}.userClassPathFirst instead.
16/07/28 10:54:00 WARN SparkConf: The configuration key 'spark.yarn.user.classpath.first' has been deprecated as of Spark 1.3 and may be removed in the future. Please use spark.{driver,executor}.userClassPathFirst instead.
16/07/28 10:54:00 INFO SecurityManager: Changing view acls to: sg226503
16/07/28 10:54:00 INFO SecurityManager: Changing modify acls to: sg226503
16/07/28 10:54:00 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(sg226503); users with modify permissions: Set(sg226503)
Exception in thread "main" java.io.IOException: YarnSparkContextClient init failed
    at org.apache.spark.sql.client.JavaSparkSQLClient.liftedTree1$1(JavaSparkSQLClient.scala:28)
    at org.apache.spark.sql.client.JavaSparkSQLClient.sparkContextClient$lzycompute(JavaSparkSQLClient.scala:19)
    at org.apache.spark.sql.client.JavaSparkSQLClient.sparkContextClient(JavaSparkSQLClient.scala:19)
    at org.apache.spark.sql.client.JavaSparkSQLClient.submitSql(JavaSparkSQLClient.scala:44)
    at org.apache.spark.sql.client.JavaSparkSQLClient$.main(JavaSparkSQLClient.scala:194)
    at org.apache.spark.sql.client.JavaSparkSQLClient.main(JavaSparkSQLClient.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.apache.spark.sql.client.JavaSparkSQLClient.liftedTree1$1(JavaSparkSQLClient.scala:23)
    ... 14 more
Caused by: java.lang.NoSuchMethodError: org.apache.spark.rpc.RpcEnv$.create$default$6()Z
    at org.apache.spark.sql.yarn.YarnSQLClient.start(YarnSQLClient.scala:134)
    at org.apache.spark.sql.yarn.YarnSQLClient.<init>(YarnSQLClient.scala:127)

**Comment by lianhuiwang** [comment]
@anayyar82 May be rpc using netty has some problem. So try to set 'spark.rpc=akka'.

**Comment by anayyar82** [comment]
sorry where exactly.. i updated in spark-defaults.conf  but same error...

**Comment by lianhuiwang** [comment]
add '--verbose' to the end of command. and see some more information.

**Comment by anayyar82** [comment]
spark-submit --verbose --class org.apache.spark.sql.client.JavaSparkSQLClient spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar spark-defaults.conf /home/sg226503/ "select 1+2"
Using properties file: /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/spark/conf/spark-defaults.conf
Adding default property: spark.serializer=org.apache.spark.serializer.KryoSerializer
Adding default property: spark.eventLog.enabled=true
Adding default property: spark.shuffle.service.enabled=true
Adding default property: spark.driver.extraLibraryPath=/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
Adding default property: spark.yarn.historyServer.address=http://bdaolc011node03.sabre.com:18088
Adding default property: spark.dynamicAllocation.schedulerBacklogTimeout=1
Adding default property: spark.yarn.am.extraLibraryPath=/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
Adding default property: spark.yarn.config.gatewayPath=/opt/cloudera/parcels
Adding default property: spark.yarn.config.replacementPath={{HADOOP_COMMON_HOME}}/../../..
Adding default property: spark.shuffle.service.port=7337
Adding default property: spark.master=yarn-client
Adding default property: spark.authenticate=false
Adding default property: spark.executor.extraLibraryPath=/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
Adding default property: spark.eventLog.dir=hdfs://bdaolc01-ns/user/spark/applicationHistory
Adding default property: spark.dynamicAllocation.enabled=true
Adding default property: spark.dynamicAllocation.minExecutors=0
Adding default property: spark.dynamicAllocation.executorIdleTimeout=60
Adding default property: spark.yarn.jar=local:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/spark/lib/spark-assembly.jar
Parsed arguments:
  master                  yarn-client
  deployMode              null
  executorMemory          null
  executorCores           null
  totalExecutorCores      null
  propertiesFile          /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/spark/conf/spark-defaults.conf
  driverMemory            null
  driverCores             null
  driverExtraClassPath    null
  driverExtraLibraryPath  /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
  driverExtraJavaOptions  null
  supervise               false
  queue                   null
  numExecutors            null
  files                   null
  pyFiles                 null
  archives                null
  mainClass               org.apache.spark.sql.client.JavaSparkSQLClient
  primaryResource         file:/home/sg226503/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar
  name                    org.apache.spark.sql.client.JavaSparkSQLClient
  childArgs               [spark-defaults.conf /home/sg226503/ select 1+2]
  jars                    null
  packages                null
  packagesExclusions      null
  repositories            null
  verbose                 true

Spark properties used, including those specified through
 --conf and those from the properties file /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/spark/conf/spark-defaults.conf:
  spark.executor.extraLibraryPath -> /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
  spark.yarn.jar -> local:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/spark/lib/spark-assembly.jar
  spark.driver.extraLibraryPath -> /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
  spark.authenticate -> false
  spark.yarn.historyServer.address -> http://bdaolc011node03.sabre.com:18088
  spark.yarn.am.extraLibraryPath -> /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
  spark.eventLog.enabled -> true
  spark.dynamicAllocation.schedulerBacklogTimeout -> 1
  spark.yarn.config.gatewayPath -> /opt/cloudera/parcels
  spark.serializer -> org.apache.spark.serializer.KryoSerializer
  spark.dynamicAllocation.executorIdleTimeout -> 60
  spark.dynamicAllocation.minExecutors -> 0
  spark.shuffle.service.enabled -> true
  spark.yarn.config.replacementPath -> {{HADOOP_COMMON_HOME}}/../../..
  spark.shuffle.service.port -> 7337
  spark.eventLog.dir -> hdfs://bdaolc01-ns/user/spark/applicationHistory
  spark.master -> yarn-client
  spark.dynamicAllocation.enabled -> true

Main class:
org.apache.spark.sql.client.JavaSparkSQLClient
Arguments:
spark-defaults.conf
/home/sg226503/
select 1+2
System properties:
spark.executor.extraLibraryPath -> /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
spark.yarn.jar -> local:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/spark/lib/spark-assembly.jar
spark.driver.extraLibraryPath -> /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
spark.authenticate -> false
spark.yarn.historyServer.address -> http://bdaolc011node03.sabre.com:18088
spark.yarn.am.extraLibraryPath -> /opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/lib/hadoop/lib/native
spark.eventLog.enabled -> true
spark.dynamicAllocation.schedulerBacklogTimeout -> 1
SPARK_SUBMIT -> true
spark.yarn.config.gatewayPath -> /opt/cloudera/parcels
spark.serializer -> org.apache.spark.serializer.KryoSerializer
spark.shuffle.service.enabled -> true
spark.dynamicAllocation.minExecutors -> 0
spark.dynamicAllocation.executorIdleTimeout -> 60
spark.app.name -> org.apache.spark.sql.client.JavaSparkSQLClient
spark.yarn.config.replacementPath -> {{HADOOP_COMMON_HOME}}/../../..
spark.jars -> file:/home/sg226503/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar
spark.submit.deployMode -> client
spark.shuffle.service.port -> 7337
spark.eventLog.dir -> hdfs://bdaolc01-ns/user/spark/applicationHistory
spark.master -> yarn-client
spark.dynamicAllocation.enabled -> true
Classpath elements:
file:/home/sg226503/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar

Using properties file: spark-defaults.conf
Adding default property: spark.sql.yarn.files=/home/sg226503/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar
Adding default property: spark.yarn.queue=root.default
Adding default property: spark.app.name=sparkSQL-client
Adding default property: spark.master=yarn-cluster
Adding default property: spark.rpc=akka
Adding default property: spark.yarn.sg226503.classpath.first=true
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/jars/avro-tools-1.7.6-cdh5.5.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.1-1.cdh5.5.1.p1168.923/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
16/07/28 11:28:37 INFO SecurityManager: Changing view acls to: sg226503
16/07/28 11:28:37 INFO SecurityManager: Changing modify acls to: sg226503
16/07/28 11:28:37 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(sg226503); users with modify permissions: Set(sg226503)
Exception in thread "main" java.io.IOException: YarnSparkContextClient init failed
    at org.apache.spark.sql.client.JavaSparkSQLClient.liftedTree1$1(JavaSparkSQLClient.scala:28)
    at org.apache.spark.sql.client.JavaSparkSQLClient.sparkContextClient$lzycompute(JavaSparkSQLClient.scala:19)
    at org.apache.spark.sql.client.JavaSparkSQLClient.sparkContextClient(JavaSparkSQLClient.scala:19)
    at org.apache.spark.sql.client.JavaSparkSQLClient.submitSql(JavaSparkSQLClient.scala:44)
    at org.apache.spark.sql.client.JavaSparkSQLClient$.main(JavaSparkSQLClient.scala:194)
    at org.apache.spark.sql.client.JavaSparkSQLClient.main(JavaSparkSQLClient.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.apache.spark.sql.client.JavaSparkSQLClient.liftedTree1$1(JavaSparkSQLClient.scala:23)
    ... 14 more
Caused by: java.lang.NoSuchMethodError: org.apache.spark.rpc.RpcEnv$.create$default$6()Z
    at org.apache.spark.sql.yarn.YarnSQLClient.start(YarnSQLClient.scala:136)
    at org.apache.spark.sql.yarn.YarnSQLClient.<init>(YarnSQLClient.scala:127)
    ... 19 more

**Comment by lianhuiwang** [comment]
from https://www.cloudera.com/documentation/enterprise/release-notes/topics/cdh_rn_new_in_cdh_55.html, Spark version of CDH-5.5.1 is 1.5. 
Please use 'spark-submit --version' check it.

**Comment by lianhuiwang** [comment]
please use 'spark.yarn.user.classpath.first true' not 'spark.yarn.sg226503.classpath.first=true'.

**Comment by anayyar82** [comment]
version 1.5.0-cdh5.5.1

**Comment by anayyar82** [comment]
sure updated... so in spark 1.5-cdh5.5.1, i can't run the program ?  what if i add dependent library in jar itself then also i can't run ?

**Comment by lianhuiwang** [comment]
OK. Please update to 1.6 version. Thanks.
I think you can install a new directory for 1.6 that just use CDH1.5's Hadoop_Home.

**Comment by anayyar82** [comment]
sure, i am doing now and will update you in few minutes. 

another question if i want to select something from Hive table let say select \* from db.table name where some condition...  like that needs to pass the query ?

**Comment by lianhuiwang** [comment]
Please use 'spark.sql.yarn.files ./target/spark-sql-yarn-0.1-SNAPSHOT-jar-with-dependencies.jar,./Mysql.jar,./Hive-site.xml'. Please add any needed files to 'spark.sql.yarn.files'.
